-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(40) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    project_id serial NOT NULL,
    block_id serial,
    planned boolean NOT NULL,
    created timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.blocks
(
    id serial NOT NULL,
    project_id serial NOT NULL,
    time_start timestamp without time zone NOT NULL,
    time_end timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    user_id serial NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    id serial NOT NULL,
    user_id serial NOT NULL,
    day_change_time time without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    "time" timestamp without time zone,
    day date NOT NULL,
    task_id serial NOT NULL,
    PRIMARY KEY (id)
);
END;